FROM openjdk:11 as build
ARG JAR_FILE=build/libs/daily-receipt-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Duser.timezone=Asia/Seoul","-Dspring.profiles.active=dev","-jar","/app.jar"]
