spring:
  datasource:
    url: jdbc:mysql://localhost:3306/receipt?characterEncoding=UTF-8&serverTimezone=UCT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

social:
  kakao:
    client-id: ENC(YhRstpqSMrFjoMvKPaY2bYEB+wseFUvNH5J/Gqra8kyQ+BfdCAjvsk93C+7B5l6/)
    client-secret: ENC(OsvS4WEFAAIJAjp2gWhnPs8cG1I6EOpudqdqmOYL/tlgWSMtY0qa8lIwWWb99vNz)

private:
  ip: "http://localhost:3000/auth/kakao/callback"

jwt:
  token:
    secret: ENC(BTkM7xq4W3pJHktgWPuVIrHvdd8uiuHMSuZmNvxtvSbY3XlLm3RBYnyj8ZeyZbo7O/v5bzlfAPQuf8k9MnYjPnTwrt04H2cH490OHV9BAZHCF3zk8rOesInQk5cSmhIMEuLBh7P1ZD4erQbdmkPRVveJFXDxR85nvQbcqwVl9jQyzhR3ETiAqJ7cpa4DZQqEPuRBkZiTZHqtGXsz7Ehx8XZ+W0qqKbnaJfoaJEQJ1nEvWfe4WvhQjc5S7+pBABHA91vr6fdugqE=)
