spring:
  datasource:
    url: jdbc:mysql://localhost:3306/receipt?characterEncoding=UTF-8&serverTimezone=UCT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

---

spring:
  config:
    import: classpath:daily-receipt-submodule/application-dev.yml
    activate:
      on-profile: dev
