spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/receipt?characterEncoding=UTF-8&serverTimezone=UCT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

social:
  kakao:
    client-id: ENC(YhRstpqSMrFjoMvKPaY2bYEB+wseFUvNH5J/Gqra8kyQ+BfdCAjvsk93C+7B5l6/)
    client-secret: ENC(OsvS4WEFAAIJAjp2gWhnPs8cG1I6EOpudqdqmOYL/tlgWSMtY0qa8lIwWWb99vNz)

private:
  ip: ENC(iK4YY6wB9qVifcQlTgckhYQpkIywPvh1)