= Daily-Receipt API Docs
:source-highlighter: highlightjs
:toc: left
:toclevels: 2

[[Todo-API]]
== Todo API

[[Todo-조회]]
=== Get Todo

targetDate가 없는 경우에는 해당 사용자가 생성한 모든 Todo List를 반환합니다

operation::get-todo[snippets='http-request,request-parameters']

[[Todo-생성]]
=== Post Todo

operation::post-todo[snippets='http-request,request-fields,http-response,response-body']

[[Todo-수정]]
=== Put Todo

operation::put-todo[snippets='http-request,request-fields,path-parameters,response-body']

[[Todo-삭제]]
=== Delete Todo

operation::delete-todo[snippets='http-request,path-parameters']

[[Account-API]]
== Account API

[[Account-조회]]
=== Get Account

operation::get-account[snippets='http-request,request-headers']

[[Account-수정]]
=== Put Account

operation::put-account[snippets='http-request,request-fields,request-headers']

[[Receipt-API]]
== Receipt API

[[Receipt-생성]]
=== Post Receipt

operation::post-receipt[snippets='http-request,request-fields,http-response,response-body']

[[Receipt-조회]]
=== Get Receipt
operation::get-receipt[snippets='http-request,request-headers']

[[Receipt-수정]]
=== Put Receipt
operation::put-receipt[snippets='http-request']